language: python
python:
  - "3.7"

stages:
  - lint
  - test

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

services:
  - postgresql

addons:
  postgresql: "12"

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --upgrade pip
        - pip install poetry
        - poetry install -v
      before_script:
        - cp monitor.example-config.yaml ~/.config/monitor.yaml
        - |
          sed -i "s|host:.*$|host: 'localhost'|" ~/.config/monitor.yaml
          sed -i "s|user:.*$|user: 'postgres'|" ~/.config/monitor.yaml
          sed -i "s|password:.*$|password: ''|" ~/.config/monitor.yaml
      after_script:
        - rm -f ~/.config/monitor.yaml
      script:
        - poetry run pytest tests
