[tool.poetry]
name = "monitor"
version = "0.1.0"
description = "Small conceptual website monitor using Kafka and PostgreSQL."
authors = ["Sören König <soeren.koenig@mailbox.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/skoenig/aiven-website-monitor"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
